feat: 图表模块开发及todotip优化
thundersdata-frontend/rn-template pull request #5
Opened 2020-04-30 02:24 UTC by tunshiyu

1 图表模块基础表格/基础流图/基础饼图开发
2 引入神威基础流图的option方法
3 优化todotip
4注释掉tabs页面的轮播图console

2020-04-30 02:31 UTC, SunshineH2 commented on src/components/ChartWrap/index.tsx
> +  const { title, padding = 12 } = props;
这个padding用px包一下

2020-05-06 06:14 UTC, chj-damon approved these changes

2020-05-06 10:24 UTC, SunshineH2 commented on src/components/CustomTag/index.tsx
> +      paddingHorizontal: 4
用px包一下

2020-05-06 10:57 UTC, chj-damon requested changes

2020-05-06 10:57 UTC, chj-damon commented on src/components/BlockItem/index.tsx
> +const BlockItem = ({ isSelected, name, onPress, style, isWithIcon }: BlockItemInter) => {
改一下名字，CustomTag

2020-05-06 10:57 UTC, chj-damon commented on src/components/CustomTag/index.tsx
> +const CustomTag: React.FC<CustomTagProps> = ({ children, style, type = 'blue' }) => {
把这个组件和上面的BlockItem合并成一个组件。他们的区别只在于是否可以点击

2020-05-06 10:57 UTC, chj-damon commented on src/components/ImgLinkItem/index.tsx
> +const ImgLinkItem = ({ source, title, content, navigateTo }: BlockItemInter) => {
什么作用？

2020-05-06 10:57 UTC, chj-damon commented on src/screens/show/components/Card/index.tsx
> +export default function Cardd() {
拼写错误

2020-05-06 10:57 UTC, chj-damon commented on src/components/SearchPicker/index.tsx
> +  if (size === 'small' || size === 'mid' || size === 'big') {
我觉得既然有size了，是不是就不需要额外传自定义的width和maxShowLength了？这种自定义的需求感觉很弱，开发人员只需要关心size一个属性就好。

2020-05-06 10:57 UTC, chj-damon commented on src/components/SearchPicker/index.tsx
> +  let listData =
useMemo包一下

2020-05-07 07:18 UTC, chj-damon approved these changes

2020-05-07 07:19 UTC, merged